### PR TITLE
Removed stray Open Sans declaration, Converted font family to variable

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by niftylettuce** [comment]
Once accepted can you please version bump and release to npm and ping me?  Thanks

**Comment by limonte** [comment]
Released: https://github.com/limonte/sweetalert2/releases/tag/v7.3.1

**Comment by niftylettuce** [comment]
one step closer to a stable [Lad](https://lad.js.org) release, thanks many @limonte ❤️ 

I spotted this bug through <https://github.com/jonathantneal/postcss-font-magician> automatically grabbing Open Sans from Google Web Fonts 😆

**Comment by niftylettuce** [comment]
can you publish to npm btw?

**Comment by limonte** [comment]
> one step closer to a stable Lad release

Wish you a lot of success with Lad :rocket: :rocket: :rocket: 

Should be published automatically, but Travis has some issue right now. Published manually.

**Pull request merged**
