### PR TITLE
Dymanically add/remove modal container from body

### PR DESCRIPTION
**Pull request by limonte**
Related to https://github.com/limonte/sweetalert2/pull/255#issuecomment-240839239

### CODE REVIEW

**Comment by limonte** [comment]
Hello @birjolaxew, 

I made some corrections and I'll be grateful if you got some time to revisit this PR. Thanks in advance!

**Comment by birjolaxew** [comment]
I won't have access to a computer for like a week. I'll have a look afterwards.

**Comment by limonte** [comment]
Okay, thanks! Review when you have time!

Enjoy your time without a computer, I can only dream about that currently :)

**Comment by birjolaxew** [comment]
Looks good to me. All tests pass, and I couldn't find any regressions.

**Comment by limonte** [comment]
Released in [v6.4.0](https://github.com/limonte/sweetalert2/releases/tag/v6.4.0) :tada: 

Thanks for for reviewing this PR @birjolaxew!

**Pull request merged**
