### PR TITLE
Proper module exporting

### PR DESCRIPTION
**Pull request by caseyWebb**
This could be breaking — but also extremely easy to remedy on the user side — so I'm not sure if you'll want it or not, but for trying to use both sweetalert and sweetalert2 (we have a huge legacy codebase) it's crucial.

I've tweaked the readme's usage section and added a `jsnext:main` to the `package.json` as well.

🍻

### CODE REVIEW

**Comment by caseyWebb** [comment]
This PR is not ready. I'm having some other issues now. I'll get those and get back here.

**Comment by limonte** [comment]
:+1:

**Comment by caseyWebb** [comment]
All is well, ready for merge

**Comment by limonte** [comment]
Thank a lot @caseyWebb for getting this done :beers:

**Comment by limonte** [comment]
[v5.2.0](https://github.com/limonte/sweetalert2/releases/tag/v5.2.0)

**Comment by limonte** [comment]
Hi @caseyWebb! could you please take a look on https://github.com/limonte/sweetalert2-webpack-demo

When I put [v5.2.0](https://github.com/limonte/sweetalert2/releases/tag/v5.2.0) [here](https://github.com/limonte/sweetalert2-webpack-demo/blob/master/package.json#L14) then I'm getting `swal is not defined` exception.

With [v5.1.1](https://github.com/limonte/sweetalert2/releases/tag/v5.1.1) all works fine.

Thank you in advance :beers:

**Comment by limonte** [comment]
@caseyWebb [fixed](https://github.com/limonte/sweetalert2-webpack-demo/commit/4bbadd73729d728dc1fc940903b9fef3bd0d73a9), sorry for bothering :)

**Pull request merged**
