### PR TITLE
Feature/use rejections option

### PR DESCRIPTION
**Pull request by ArlyMathiasen**
This should resolve issue #485 
please review

### CODE REVIEW

**Comment by mattbrunetti** [comment]
Correction: This fixes just the first part of #485, dealing with promises returned by swal, as requested. The issue should remain open to discuss the second part, dealing with promises returned **to** swal by `preConfirm` and `inputValidator` options.

**Comment by limonte** [comment]
Great job! Looks perfect to me. Special thanks for covering the new code with tests.

Please go ahead with the same approach for `preConfirm` and `inputValidator` options.

**Comment by limonte** [comment]
I released https://github.com/limonte/sweetalert2/releases/tag/v6.6.3 yesterday with this change, take a look.

Please feel free to submit any changes for this PR ot the PR related to the same approach for `preConfirm` and `inputValidator` options.

**Comment by toverux** [comment]
This has fallen under my radar :) I've just updated the TypeScript definition file and the README to take `useRejections` in account.
Thanks @ArlyMathiasen && @mattbrunetti for that feature I will totally use :)

**Pull request merged**
