### PR TITLE
Add onInit and onOpen callbacks

### PR DESCRIPTION
**Pull request by g0ral**

### CODE REVIEW

**Comment by limonte** [comment]
Any description here? Give us an example where you can't achieve what you want without these callbacks.

**Comment by g0ral** [comment]
I'm adding custom datepicker in modal and I needed to call datepicker script on element in description HTML.

onInit is useful when you want to modify / run custom scripts on html in modal
onOpen can be useful when you want to run some js code on modal when it is open

**Comment by limonte** [comment]
Which datepicker plugin are you using?

**Comment by g0ral** [comment]
https://chmln.github.io/flatpickr/ for one example

**Comment by limonte** [comment]
Works perfectly without `onInit` and `onOpen`: https://jsfiddle.net/1drfdqg7/1/

**Comment by g0ral** [comment]
Whoops, you are right :) I have overcomplicated it. Pull request can be closed.

**Comment by limonte** [comment]
Thanks anyway, further users can google this PR and see my jsfiddle :)

**Comment by limonte** [comment]
there are now `onOpen` and `onClose` parameters

**Pull request closed without merging**
