### PR TITLE
Add position and grow parameters

### PR DESCRIPTION
**Pull request by acupajoe**
Fixes [#664](https://github.com/limonte/sweetalert2/issues/664)

### CODE REVIEW

**Comment by limonte** [comment]
Let's discuss the design of this feature a little bit more. There are a lot of possible positions users might want, e.g. this one:



This is the real use-case which I would like to support. SweetAlert2 should support both horizontal/vertical positioning, as well as the possibility of flex grow.

**Comment by acupajoe** [comment]
I like that screenshot! Makes the use-case from #654 a lot more tangible.

Options: `top`, `top-left`, `top-right`, `center`, `center-left`, `center-right`, `bottom`, `bottom-left`, and `bottom-right`. 

The question becomes, should `top`, `bottom`, `left,` and `right` be centered as a standard alert or grow to fill the screen. I'll push for having them center by default and add an addition `grow: true|false` parameter

Thoughts?

**Comment by acupajoe** [comment]
@limonte Added your suggestions! I'm not entirely sure how to add it into the testing environment.

**Comment by limonte** [comment]
Holy flex! This is almost exactly what I wanted! You are awesome @acupajoe :rocket: 

Question: would it be better if for vertical alignment we will use `middle` instead of `center`? Just to be aligned with the native [vertical-align](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align).

Also, could you please copy-paste docs for new parameters from README.md to https://github.com/limonte/sweetalert2/blob/master/index.html#L480

Many thanks for handling this in such a nice and well-maintainable way :beers:

**Comment by limonte** [comment]
The upcoming feature based on this one could be `grow: 'fullscreen'` :rocket: 

This is a HUGE improvement, I'm so excited about it!

**Comment by acupajoe** [comment]
@limonte You're absolutely right, chrome doesn't punish me for using `center` so I forgot that was the proper syntax! I'll add fullscreen in too while I've got it open.

**Comment by limonte** [comment]
> I'm not actually using vertical-align, flex uses center instead of middle!

Let's keep it in that way, `center` it is, both for horizontal and vertical :+1:

**Comment by acupajoe** [comment]
@limonte annnnd there's fullscreen support. Let me know if I can add anything else! Excited for this to be added in.

**Pull request merged**
