### PR TITLE
Add dismissal handling to readme

### PR DESCRIPTION
**Pull request by birjolaxew**
Added documentation explaining how to handle rejections to avoid errors. See #221 and #177.

### CODE REVIEW

**Comment by limonte** [comment]
Thank you so much @birjolaxew for this PR! :beers: :+1:

**Comment by limonte** [comment]
@birjolaxew I really like your contributions to swal2 package. Would you like to become the contributor? #130

**Comment by birjolaxew** [comment]
@limonte Sure. I can't guarantee my activity on the long term, but I'll stick around for a bit.

**Comment by limonte** [comment]
@birjolaxew I'm not looking for guarantees, welcome :)

**Comment by imdadturi** [comment]
it doesn't work for me... still getting 

> Error: Uncaught (in promise): cancel

**Pull request merged**
