### PR TITLE
Set `useRejections` to `false` by default

### PR DESCRIPTION
**Pull request by limonte**
Connected to #661 

Related PR: #485

### CODE REVIEW

**Comment by toverux** [comment]
Shouldn't we remove entirely the old behaviour?

Advantages:

 - less code to maintain
 - less code to test
 - less to document
 - bundle size slightly reduced

Disadvantages:

 - More work for users to port from v6 to v7.

In any case, I hope that at some point we'll drop the old behaviour, I don't see it as a feature but more like technical debt. Maybe in a next major? In that case, we could add a deprecation warning when the user passes `useRejections: true`.

**Comment by limonte** [comment]
> Shouldn't we remove entirely the old behaviour?

I'd say yes. It's a new major and it's okay to introduce one more not-so-big breaking change.  Any objections from others?

**Comment by zenflow** [comment]
I'd say changing the default is a not-so-big breaking change, but removing the option and forcing the new behavior is a major breaking change, and will require significant refactoring in some projects.

I think it would be really dev-friendly if we gave users a grace period of one major iteration, where they can still be up-to-date with the newest version, and they can update their usage, gradually and or when it's convenient.

If we did that, a deprecation warning when the user passes `useRejections: true` would be the way to go.

**Comment by zenflow** [comment]
@limonte Will examples in `index.html` be updated in regards to this?

**Comment by limonte** [comment]
> I think it would be really dev-friendly if we gave users a grace period of one major iteration, where they can still be up-to-date with the newest version, and they can update their usage, gradually and or when it's convenient.

Objection sustained. Let's keep being friendly to the Community and deprecate the feature instead of dropping it :+1:

> Will examples in index.html be updated in regards to this?

Yes, I was planning to handle https://github.com/limonte/sweetalert2/pull/674 and then update examples.

**Comment by acupajoe** [comment]
I second a depreciation over a drop as well

**Comment by zenflow** [comment]
@limonte I think there should be a `console.warn('[sweetalert2] useRejections is deprecated and will be removed in the next major release.')` for when someone passes `userRejections: true`, as suggested by @toverux. Let's make totally sure everyone still using this option is aware that support ends soon, so they can use this grace period to upgrade their usage.

I'll make a PR for this at lunch today, and I'll include something similar for `expectRejections` off-the-bat.

**Pull request merged**
