### PR TITLE
spacer background

### PR DESCRIPTION
**Pull request by luckyraul**

### CODE REVIEW

**Comment by limonte** [comment]
Any description for this change?

**Comment by luckyraul** [comment]
to force it to be transparent even if hr has background

**Comment by birjolaxew** [comment]
Are there any browsers where `<hr>`'s have backgrounds by default?

**Comment by luckyraul** [comment]
As far as I'm concerned - no, but in that class you also set colour for "not default browser setting"
This is for only for prevention override.

**Comment by limonte** [comment]
Sounds like a real case, thanks for the explanation. Please exclude `dist/sweetalert2.css` from the PR and we're good to go with merge :+1:

**Comment by luckyraul** [comment]
updated

**Comment by limonte** [comment]
Thanks :beers:

**Pull request merged**
