### PR TITLE
Fixed enterKey event's conditional

### LINKED ISSUE #720: allowEnterKey:false is not working for IME keyboard
In the IME used for Japanese key input, the user uses the enter key to confirm the input candidate.
Therefore, if you handle a click event depending on whether the contents of e.key is 'Enter' or not, you can not distinguish between character input confirmation operation and Submit.
In addition, users using Japanese input can not prevent Submit by EnterKey even if you use allowEnterKey: false

### PR DESCRIPTION
**Pull request by kazumanagano**
Fix #720

### CODE REVIEW

**Comment by limonte** [comment]
Thanks @kazumanagano, but I can't accept the deprecated way to handle keyboard events.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

image

**Comment by kazumanagano** [comment]
Sorry, I don't know keyCode is deprecated.
I fixed the way by using KeyboardEvent.isComposing.

**Comment by limonte** [comment]
Many thanks @kazumanagano!

**Comment by limonte** [comment]
Released in [v7.0.1](https://github.com/limonte/sweetalert2/releases/tag/v7.0.1)

:warning:  If you upgrading from v6.x please make sure you read the release notes with some breaking changes for the new major release: [v7.0.0](https://github.com/limonte/sweetalert2/releases/tag/v7.0.0)

**Pull request merged**
