### PR TITLE
Injects the compiled SCSS into the dom rather than the rollup-compile…

### LINKED ISSUE #673: Problem closing the modal in Android's default browser
I'm having trouble closing the modal using the standard android browser.

The test was:
1- Open the site https://limonte.github.io/sweetalert2/ in the Android browser. (I used AVD API 22 / Android 5.1 and another test in Asus Zenfone 2 Android 5.0)
2- Click the "Show success message"
3- Click the "OK" button. The modal does not close. :(

No errors were shown on the console. I already tried to use core-js and it still did not work.

Thank you.

### PR DESCRIPTION
**Pull request by samturrell**
…d SCSS

Also cleaned up a few inconsistencies with semi-colons and my IDE screaming at me for various things.

Fixes #673 (I hope)

### CODE REVIEW

**Comment by samturrell** [comment]
Decided to pull in the compiled CSS rather than the SCSS so that we don't have to duplicate the gulp styles pipeline in the rollup pipeline.

**Comment by samturrell** [comment]
Also, skimming through the codebase, the main entry point is starting to grow quite large. Might be worth seeing what we can do about breaking up the logic into sub-modules for future maintainability as I did with my first contribution to somewhat follow the single responsibility principle.

**Comment by limonte** [comment]
That was fast!!

> Also cleaned up a few inconsistencies with semi-colons and my IDE screaming at me for various things.

I like your IDE! What is it? 

> Also, skimming through the codebase, the main entry point is starting to grow quite large. Might be worth seeing what we can do about breaking up the logic into sub-modules for future maintainability as I did with my first contribution to somewhat follow the single responsibility principle.

Agree.

**Comment by samturrell** [comment]
I use IntelliJ IDEA, but all of the jetbrains family are great!

**Pull request merged**
