### PR TITLE
Rollup: Export named "default"

### LINKED ISSUE #390: sweetalert2_1.default is not a function
I'm trying to switch from sweetalert to sweetalert2. 

Is anyone using this successfully with webpack2 and angular2?

Whatever i try, i always get this error: 

`Error in :0:0 caused by: sweetalert2_1.default is not a function`

My component is the most simple i can guess

```
import swal from "sweetalert2";
import {Component, OnInit} from "@angular/core";

@Component({
    selector: "dashboard",
    template: require("./dashboard.template.html")
})
export class Dashboard implements OnInit {
    ngOnInit() {
        swal("Hi from webpack!");
    }
}
```

The code generated by webpack looks like this:

```
var sweetalert2_1 = __webpack_require__(1334);
var core_1 = __webpack_require__(0);
var Dashboard = (function () {
    function Dashboard() {
    }
    Dashboard.prototype.ngOnInit = function () {
        sweetalert2_1.default("Hi from webpack!");
    };
    Dashboard = __decorate([
        core_1.Component({
            selector: "dashboard",
            template: __webpack_require__(1387)
        }), 
        __metadata('design:paramtypes', [])
    ], Dashboard);
    return Dashboard;
}());
exports.Dashboard = Dashboard;
```

EDIT: 
**When replacing the import with require the bundle is fine and it works** 

So replace 
`import swal from "sweetalert2";`
with
`var swal = require("sweetalert2");`

But then, no TypeScript Type definitions are recognized :/

Does anyone know how to workaround?

### PR DESCRIPTION
**Pull request by limonte**
Fix #390

### CODE REVIEW

**Comment by toverux** [comment]
@limonte sorry for the delay, had no time to work on SweetAlert those last two days :/
I approved the changes. I've already tested it with TypeScript and ES 2015 and it works.

Be aware that some *old* setups, like a project based on an old Browserify version, will break with this change.

For example, `var sweetalert = require('sweetalert2');` will work on most setups today (ES 2015 with its named default export is 2015 and we're almost in 2017), but older projects may encounter issues, and will have to change to `var sweetalert = require('sweetalert2').default;`.

Nothing terrible, just hoping this won't happen. Anyway, named exports are the best today!

**Comment by limonte** [comment]
Thank you @toverux! I should figure out what is the reason of broken build, after that I'll merge this change.

**Comment by toverux** [comment]
@limonte Yes I wanted to add a comment about the tests, but my Internet blew up at that moment. They're probably failing for the reason I exposed in my first comment ; when those tests have been configured? Very sorry, I don't have much time to help until tuesday :/

**Comment by limonte** [comment]
@toverux unfortunately, I can't get this working in non-module way:

```html
<script src="./dist/sweetalert2.js"></script>
```

`swal` will be

**Comment by limonte** [comment]
No rush @toverux, take a look on this issue when you'll be able.

**Comment by toverux** [comment]
Thanks @limonte, I work too much with module bundlers, forgotting that some people use <script>... I will fix this and we should be fine.

**Comment by toverux** [comment]
@limonte Here we go. I think that's the most compatible solutions atm, given that we're not exporting multiple symbols, but a namespace.
This hack in `src/sweetalert2.js` should bring compatibility to TypeScript 1/2 with all module bundlers, without breaking other environments (fingers crossed).
Not very pretty since it brings build-related problematics into the original source, but it's the easiest.

**Comment by limonte** [comment]
Hello @toverux! I really appreciate that you're taking part in this complex part of plugin development. :beers: :beers: :beers:

```js
sweetAlert.default = sweetAlert
```

this is the hacky trick :)

---

I'm wondering how are you generating files in dist folder. If I pull the `fix/390` branch and tun `gulp` it will generate files which are different from those you've committed.

---

PS. Probably you want to setup your Git name, currently you're Mr. Unknown:

**Comment by toverux** [comment]
> I'm wondering how are you generating files in dist folder. If I pull the fix/390 branch and tun gulp it will generate files which are different from those you've committed.
Yes, I've also noticed that. Try to update all your devDependencies, it looks like that some helper code is no longer included by some build tool.

> PS. Probably you want to setup your Git name, currently you're Mr. Unknown
Hah, yes thanks, I've recently reinstalled my OS and lost some configs :D

**Comment by limonte** [comment]
> Yes, I've also noticed that. Try to update all your devDependencies, it looks like that some helper code is no longer included by some build tool.

Nice! -300 LOC with 0 effort :)

**Pull request merged**
