### PR TITLE
Mention collaborators in README and docs page

### PR DESCRIPTION
**Pull request by limonte**
@toverux @birjolaxew @samturrell @acupajoe @patrickhlauke I'm proud of working with you guys. You are all expert with different skills I lack. Without you this plugin would not be so elegant, accessible and easy-to-use!

I'm more than happy to mention you both in README and examples page.

image

If for any reason any of you don't want to be mentioned there, please let me know.

Keep up making this world a better place :rocket:

### CODE REVIEW

**Comment by limonte** [comment]
I love different skills of you guys! Everyone of you should get a small :dollar: from me, grab a :beer: / :coffee: / :tea: and have a great day!

image

**Comment by limonte** [comment]
PS. did you know that swal2 is already more popular than original swal:

- swal: 
- swal2: 

:muscle: :muscle: :muscle:

**Comment by patrickhlauke** [comment]
Completely unnecessary, but a lovely gesture nonetheless. Thank you 👍

**Comment by toverux** [comment]
Yeah, thanks a lot @limonte :smile:
You already know my feelings about the library and your work :) Let's <s>make SweetAlert great again</s> keep SweetAlert great!

Thanks also to the other collaborators here, because without all of you, this library probably wouldn't have been as popular as the original one (and even a little bit more popular now, let's continue on that path, it's a constant effort). I'm also proud to have chosen this little community as my first open source project I contribute to (more than 1 or 2 commits, I mean).

**Comment by samturrell** [comment]
You didn't have to do that @limonte, but thank you!

Well done to everybody involved! 🎉

**Pull request merged**
