### PR TITLE
IOS Fix

### PR DESCRIPTION
**Pull request by yeomann**
Fix is under sweetAlert.init function, according to my sublime starting from 1180 line number to 1223 line number.
Also browserSync added in gulpfile for easier cross platform testing.

### CODE REVIEW

**Comment by samturrell** [comment]
Hi @yeomann,

Would you mind reverting the indentation style to two spaces as it was before? It's made this commit unnecessarily big and made changes to every line, so I can't even properly see what you did. (Also almost crashes the github diff view)

@limonte - Maybe we should prepare a .editorconfig and accompanying contributor style guide so this doesn't happen in future?

**Comment by yeomann** [comment]
Hi @samturrell,
made those indentation to two space. So the reason behind using two space is too make commit less big?

**Comment by samturrell** [comment]
It's just code consistency. It's currently two spaces so let's keep it two spaces until decided otherwise. Else we'll end up with people changing from 2 space to 4 space over and over depending on their personal code styles, which is a nightmare for checking PR's and will be an even bigger nightmare if you end up getting a merge conflict.

RE: Line too long, I'll be fixing that some time this weekend.

**Comment by limonte** [comment]
Soryy @yeomann but this PR has too many mistakes. In future please make PRs with changes only in code which is related to issue you're trying to fix.

**Comment by yeomann** [comment]
sorry guys didn't know that stupid four or two lines indentation could create such fuss.

**Pull request closed without merging**
