### PR TITLE
Add 'growl' (toast) feature

### PR DESCRIPTION
**Pull request by acupajoe**
Migration from #670 (now on root repo instead of my own)

For #663:

example

*Note:* this PR is still a work in progress, I'm placing it here to allow for feedback.

Desired Features before Merge:
- [x] any screen position
- [x] click toast to close it (if no buttons available)
- [x] remove background interference / focus
- [x]  style all icons ( and animations )
   - [x] info icon
   - [x] question icon
   - [x] warning icon
   - [x] error icon
   - [x] success icon
- [x]  add more 'popup-y' animations
- [x]  style toast with `title` and `text` params set
- [x]  verify keyboard input shouldn't be stolen from user
- [x]  either test with swal's available inputs (and style them) or disallow inputs

~~multiple toasts (?)~~ <-- this may be unfeasible without rewrite

### CODE REVIEW

**Comment by limonte** [comment]
Rebased to master :octocat:

**Comment by acupajoe** [comment]
@limonte I'm not sure about supporting inputs inside of these toasts - there's partial support for them currently, but is that a use case we should support?

**Comment by kgrvr** [comment]
Can you provide a flag to remove backdrop when Toast gets visible?

**Comment by acupajoe** [comment]
@kgrvr not a flag - it just removes the backdrop entirely. Is there a use case for needing a backdrop on a toast?

**Comment by kgrvr** [comment]
@acupajoe No.. But there's also no option in swal options to remove backdrop.
Secondly, when it removes backdrop completely, is the other area apart from toast clickable?

**Comment by acupajoe** [comment]
@kgrvr correct - the only clickable area is the toast itself. And you're right, in a standard modal there isn't a flag to hide it. However, you can write a class to add to it that hides the background.

**Comment by kgrvr** [comment]
@acupajoe Yup, you can hide surely hide it. But the problem is the clicking of mouse button. Removing of backdrop is of no use if the user is not able to click the area behind it.

**Comment by acupajoe** [comment]
@kgrvr true, if that's a feature you want to see added you'll need to open an issue request for it! Toasts are a separate concern. Thanks!

**Comment by kgrvr** [comment]
@acupajoe Surely will add an issue request for that. ☺️
Between, when is this toast feature going to be added in the master?

**Comment by acupajoe** [comment]
@kgrvr waiting for some final reviews to be added as to what we should do about handling inputs inside of a toast - but hopefully by early next week!

**Comment by toverux** [comment]
Love the new animation, good job! :smile:
Could you expand on "there is partial support for the inputs"? Without looking at the details I'd say that, apart from the styling, their behaviour shouldn't change (except for auto-focus).

**Comment by acupajoe** [comment]
@toverux I'm not entirely sure how they should be styled? In the toasts I transitioned into a vertical layout instead of horizontal. But I'm not sure if that is the best option?

**Comment by acupajoe** [comment]
# Inputs

I believe this is the last section of the PR to be approved - provided it is, I'd vote for merging it in, along with needing some adjustments to the readme to advertise this functionality.

**Text input**
text

**Input with Error**
url

**Textarea**
textarea

**Select**
select

**Radio**
radio

**Checkbox**
checkbox

**File** (I don't think I'm happy with this one)
file

**Range**
range

**Chaining**
chaining

**Comment by limonte** [comment]
Almost ready to merge!

1. Before merging this I would like to fix https://github.com/limonte/sweetalert2/issues/673 and release `v6.11.3` so users with `^6.0.0` dependency are safe and sound.
2. The same as for https://github.com/limonte/sweetalert2/pull/681 - since there's no backdrop and the default background is white, something like `box-shadow: 0 0 10px $swal2-overlay` will improve the UX.
3. There's one small issue, I added a test and pushed it to this branch: https://github.com/limonte/sweetalert2/pull/672/commits/2e4b47c98cea7e8808c632c6e8733cd3d0e3d70a

PS. Gifs are awesome, I'll include them in the v7 release notes!

**Comment by acupajoe** [comment]
@limonte all that's left is #673 which it seems you're looking into!

**Comment by limonte** [comment]
I'm planning to merge this PR by the end of the day, any objections from anyone?

**Pull request merged**
