### PR TITLE
Better form support 

### PR DESCRIPTION
**Pull request by johanwilfer**
Some fixes to better surpport forms in sweetalert:
- Support tab to select's
- If there is invisible/hidden elements, tab to the next/prev one
- Don't use p-tags to encapsulate html (but use it for non-html).
- Focus the first visible input/button on swal().

### CODE REVIEW

**Comment by limonte** [comment]
Thank you @johanwilfer for this contribution.

On first sight looks good for me, let me test changes before merge :)

**Comment by johanwilfer** [comment]
Great! And thank you for creating this fork. I was a bit sad looking at the original repro and trying to get forms to work.

This makes sweetalert possible to use with custom forms for me.
I use jquery to hide/show form-rows that are relevent as feedback to the user as he fills out the form. This also makes it possible to hide the entire row (as in bootstrap forms), and sweetalert will try the next one if the one that should be selected is hidden in any way.

**Comment by limonte** [comment]
Great work :+1:

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2/releases/tag/v0.3.0

**Pull request merged**
