### PR TITLE
Add expectRejections param

### PR DESCRIPTION
**Pull request by zenflow**
Work in progress. Expected to close off issue #485. Please review.

### Notes

- I fixed a bug in the initial useRejections implementation from PR #525, and also did some refactoring of it
- I'm exposing a new public method adaptInputValidator so users who have inputValidators using the old API can start using the new API without having to refactor all of their old inputValidators right away.
- When I enabled the new behavior in the defaults (set expectRejections to false) none of the tests failed, so I changed the 'validation error' test to validate the old behavior, and created a corresponding test 'validation error /w expectRejections=false'. Also added a test 'does not swallow errors in user-defined functions /w expectRejections=false'.
- I was tempted to add support for sync inputValidators and preConfirms right in this PR but I'll follow up with that in a separate PR

### Question

As it is now, when expectRejections=false, preConfirm functions have no way to signal a validation error. It only signals the value that should be returned by swal. Should we fix that? Or for the sake of a simpler API should we say only inputValidators can signal validation errors? If you want to fix it, what API would you like to see?

How about...?

```
async function preConfirm (value) {
  if (isBad(value)) {
    return {validation: 'bad!'};
  } else {
    return {value: someTransform(value)}
  }
}
```

### CODE REVIEW

**Comment by zenflow** [comment]
#### The inputValidator API /w expectRejections=true (current behavior)

```
function inputValidator (input) {
  return input === '' ? Promise.reject('Must not be blank')
    : input.length > 30 ? Promise.reject('Must not be over 30 characters')
    : Promise.resolve()
}

// as an async function

async function inputValidator (input) {
  if (input === '') {
    throw 'Must not be blank'
  } else if (input.length > 30) {
    throw 'Must not be over 30 characters'
  }
}

```

Note that the `throw 'text'` statements violate the [no-throw-literal eslint rule](https://eslint.org/docs/rules/no-throw-literal)

#### The inputValidator API /w expectRejections=false (newly enabled behavior)

```
function inputValidator (input) {
  return Promise.resolve(input === '' ? 'Must not be blank'
    : input.length > 30 ? 'Must not be over 30 characters' 
    : null)
}

// or as an es-next async function

async function inputValidator (input) {
  return input === '' ? 'Must not be blank'
    : input.length > 30 ? 'Must not be over 30 characters' 
    : null
}

**Comment by toverux** [comment]
So I'm planning the v.3 of [NgSweetAlert2](https://github.com/toverux/ngsweetalert2) which will go deeper and smarter in its integration with SweetAlert2.

So I hade to take a closer look to the preConfirm/inputValidator APIs and given that there are important (but very welcomed) changes, I'll have to wait for Swal2 v.7.

### `inputValidator`

I'm 100% for the new inputValidator API based on `null` when validation passes, and a real value (a string here) for user errors. Angular has the same, by the way (with an object instead of the string, for multiple inputs).

### `preConfirm`

> How about...?

```js
async function preConfirm (value) {
  if (isBad(value)) {
    return {validation: 'bad!'};
  } else {
    return {value: someTransform(value)}
  }
}
```

I don't like it. I'd say I'd prefer that preConfirm wouldn't be able to return validation errors. Only technical error (reject) or transformed value (resolve).

If the user wants to display a validation error, they still have access to the vast `swal.*` API.

```js
preConfirm() {
    return callMyApi().catch(() => swal.showValidationError('callMyApi has lamentably failed.'));
}
```

```js
swal({
    preConfirm() {
        return callMyApi();
    }
}).catch((err) => {
    swal('Error', 'callMyApi has failed, again', 'error');
})
```

KISS.

Good job, btw! v.7 will be remembered for its significantly improved control flow :)

**Comment by zenflow** [comment]
My god, still have commits to files in `dist/`. Very sorry about that all. Don't know how I managed that... 😛

**Comment by zenflow** [comment]
@toverux Yeah, I think the API you put forward is simpler and better. 

So if `showValidationError` is called during `preConfirm` (and not cancelled out by `resetValidationError`) the dialog will stay opened.

I think it's useful knowledge that you can do this so I'll be sure to document it.

**Comment by zenflow** [comment]
I'll close this PR now, since I'm going to rebase my work and open another PR (That one's the one!)

**Pull request closed without merging**
