### PR TITLE
Added inputAttributes definition

### PR DESCRIPTION
**Pull request by Fkscorpion**
I tried to use inputAttributes in my Angular2 project and the Typescript compiler gave me an error, because the definition was missing, so I added it :)

### CODE REVIEW

**Comment by limonte** [comment]
Thanks a lot @Fkscorpion!

**Comment by toverux** [comment]
Tyhank you @Fkscorpion, I forgot that property since it wasn't mentioned in the docs :/
But `any` is a bit loosely typed... An interface already exists for <input>'s attributes in TypeScript's standard DOM typings : https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts#L5198

**Comment by Fkscorpion** [comment]
@toverux Sorry didn't know that, I'm fairly new to TypeScript yet but I agree!
That would maybe be a better solution!

**Comment by toverux** [comment]
Not a problem @Fkscorpion, btw I've just opened #467 where I'm explaining my research on the topic.
Thanks for having pointed the missing option anyway! :+1:

**Pull request merged**
