### PR TITLE
Add logo to readme

### PR DESCRIPTION
**Pull request by acupajoe**
Adds a swal2 logo to the readme - because it looks better! Kinda lame that you can't do that in regular markdown flavor. But if github renders it this way... I'd say that's more important.

[Doin' it live!](https://github.com/acupajoe/sweetalert2/tree/feature/add-image-logo)

### CODE REVIEW

**Comment by toverux** [comment]
Lovely! But I find the `<br>` to be useless here:

image

**Comment by acupajoe** [comment]
@toverux I've updated it - thanks for the feedback!

**Comment by limonte** [comment]
Lovely!

**Comment by limonte** [comment]
The perfect Angular-variation of this logo: https://github.com/sweetalert2/ngx-sweetalert2/commit/719a422490c9b2674544ee8386a65a152910fb42

**Comment by toverux** [comment]
Haha, thanks :smile:

**Pull request merged**
