### PR TITLE
Modules support

### PR DESCRIPTION
**Pull request by Tonkpils**
Fixes https://github.com/limonte/sweetalert2/issues/116

I have tested this out locally with my `ember-sweetalert` project and I'm going to be testing with another project that imports `ember-sweetalert`. 

Let me know if you'd like me to make any changes

### CODE REVIEW

**Comment by limonte** [comment]
Thank you so much @Tonkpils! Let me up to 24h to educate myself a little bit more about ES6 and Babel and leave comments on your PR.

Nicely done at first sight!

**Comment by limonte** [comment]
@Tonkpils I know that changes you made in https://github.com/limonte/sweetalert2/pull/131/commits/015412e87b4cdc3c62f304b157f17b3cc305a289 are needed in dev environment. But if we merge that commit [swal2 github pages](https://limonte.github.io/sweetalert2/) will stop working.

**Comment by Tonkpils** [comment]
@limonte we could make it so it works for both GH and dev. I see that in GH pages things are symlinked from example out. Could we instead move out the `index.html` and reference the correct file paths?

**Comment by Tonkpils** [comment]
I'll move that commit out of this PR though since it's unrelated anyway

**Comment by limonte** [comment]
I expected more changed lines, but you're @Tonkpils rock! With small changes in code you added modules support! 

Please remove https://github.com/limonte/sweetalert2/pull/131/commits/015412e87b4cdc3c62f304b157f17b3cc305a289 from this PR and we're ready to merge and publish v3.0.0 :)

**Comment by limonte** [comment]
@Tonkpils 

> we could make it so it works for both GH and dev. I see that in GH pages things are symlinked from example out. Could we instead move out the index.html and reference the correct file paths?

Done in https://github.com/limonte/sweetalert2/commit/898c6c200f085f439f4c355d34144ecc951247d3

**Pull request merged**
