### PR TITLE
iOS Scroll Overflow Fix

### PR DESCRIPTION
**Pull request by acupajoe**
Pros: Should fix the iOS issue (works on my simulator at least)
Cons: Can no longer scroll the background when the swal is open (is this desired functionality?)

### CODE REVIEW

**Comment by acupajoe** [comment]
#136 #142 #143

**Comment by limonte** [comment]
Thank you @acupajoe for this PR! Seems good to me, let me a couple of hours to test it on iPad.

One thing - please exclude all changes in dist/* files from PR (see https://github.com/limonte/sweetalert2/issues/148)

**Comment by acupajoe** [comment]
@limonte let me know what your tests find! I've updated the PR and squashed commits.

**Comment by limonte** [comment]
@acupajoe I merged this code to `gh-pages` branch to test, you check it yourself here https://limonte.github.io/sweetalert2/

Unfortunately, on my iPad we're still having the same bug.

**Comment by acupajoe** [comment]
@limonte http://stackoverflow.com/a/24670659/3629438?

**Comment by limonte** [comment]
@acupajoe I'm not sure how can we apply that answer to this issue.

**Comment by carter-thaxton** [comment]
I just tried this, and this fix only seems to prevent scrolling of the background.  The screen still 'jumps' and scrolls vertically to the center of the page when the keyboard is focused, which is the main problem identified by #136.

**Comment by limonte** [comment]
@carter-thaxton thanks for confirming! I have the same result.

**Comment by acupajoe** [comment]
@limonte, @carter-thaxton appreciate it guys, I'll keep looking into it!

**Comment by acupajoe** [comment]
Have made no additional progress on this: am stuck like everyone else. Am closing PR in the meantime, will reopen if solution is found.

**Pull request closed without merging**
