### PR TITLE
Fix for button margin on mobile view

### PR DESCRIPTION
**Pull request by bluefindata**
When the buttons are too wide for the popup, they stack without any spacing.

sweetalert-button-issue

### CODE REVIEW

**Comment by limonte** [comment]
I don't see how this change fixes anything. Could you please add some description and maybe screenshots which will help to understand the reason of increasing `margin-top` for buttons?

**Comment by bluefindata** [comment]
@limonte Sorry about that, I added to the description.

**Comment by limonte** [comment]
Oh, I see! Thanks for catching this visual issue @bluefindata !

With this change, you're solving the vertical space between buttons, but in the same time, the gap between the content and buttons will be increased.

Most probably, the adjacent selector is what we want here: 

```css
.swal2-styled + .swal2-styled {
  margin-top: 15px;
}
```

This means that, if a `.swal2-styled` button comes after another `.swal2-styled` button, there will be 15px margin in between.

Could you please amend your PR so we can test it out?

**Comment by bluefindata** [comment]
I haven't used that selector before, thank you for the tip 👍

**Comment by limonte** [comment]
Nice! I'll include this change in the next release. Thanks @bluefindata !

**Comment by limonte** [comment]
Available in [v6.4.1](https://github.com/limonte/sweetalert2/releases/tag/v6.4.1) :tada:

**Pull request merged**
