### PR TITLE
Add expectRejections parameter, defaulting to false

### PR DESCRIPTION
**Pull request by zenflow**
Resolves Issue #485 finally

1. Rebased & updated my work from #674 (please re-review changes)
2. Added "Support for sync `inputValidators` and `preConfirms`"
3. Made a change to "Succeed after preConfirm finishes only if no validation error is shown (applies only to expectRejections: false)" (as per discussion with @toverux in PR #647)

We still need (before or after merging):

~~1. Deprecation warning. Pending updates from PR #699.~~
~~2. Tests for `preConfirm` param. There never were any.~~
~~3. Documentation updates.~~

### CODE REVIEW

**Comment by zenflow** [comment]
So with the new behavior, these...

```
async function inputValidator (input) {
  if (input === '') {
    throw 'Must not be blank'
  } else if (input.length > 30) {
    throw 'Must not be over 30 characters'
  }
}

async function preConfirm (input) {
  if (isBad(input)) {
    throw 'bad!'
  } else {
    return someTransform(input)
  }
}
```

... become these ...

```
async function inputValidator (input) {
  return input === '' ? 'Must not be blank'
    : input.length > 30 ? 'Must not be over 30 characters' 
    : null
}

async function preConfirm (input) {
  if (isBad(input)) {
    swal.showValidationError('bad!')
  } else {
    return someTransform(input)
  }
}
```

And you can remove the `async` keyword and they work the same :)

**Comment by zenflow** [comment]
The failing test 'modal shows up' is flaky in my local testing

this sometimes happens
image
then i refresh and it's fine
image

If we somehow just triggered another build it would probably pass, but we should look into fixing that test.

**Comment by limonte** [comment]
1. Nicely done @zenflow :+1:  
2. Don't worry about failing test, that's out of scope of this PR
3. Could you please document the `expectRejectons` parameter in [README.md](https://github.com/limonte/sweetalert2/blob/master/README.md) and [index.html](https://github.com/limonte/sweetalert2/blob/master/index.html)?

**Comment by zenflow** [comment]
1. Thanks @limonte!
2. Agreed
3. Absolutely, I should be able to do so tonight
3. Agreed

**Comment by zenflow** [comment]
Alright, made changes to index.html, README.md and sweetalert2.d.ts
- Documenting the new option
- Updating documentation and examples of the inputValidator and preConfirm functions to reflect the new default behavior.

@toverux How can I indicate in sweetalert2.d.ts that a function may or may not return a promise?

**Comment by limonte** [comment]
Yay! New milestone achived!

image

Congrats to everyone! :muscle:

**Comment by zenflow** [comment]
I think this is ready to merge, aside from a tweak to sweetalert2.d.ts (see my above question for @toverux)

@limonte Agree/disagree? How does it look? Any more changes you want to see?

**Comment by toverux** [comment]
Uh, sorry, I missed your question! You can do something like that:

```typescript
type ValidationError = string | null; // null allows null for users in null-strict mode

interface SweetAlertOptions {
    inputValidator?: (input: any) => ValidationError | Promise<ValidationError>;
    preConfirm?: (input: any) => any | Promise<any> | void; // void's unnecessary because of any, but it's good to be explicit!
}
```

**Comment by zenflow** [comment]
@toverux 

There's no `ValidationError` type in the file yet, but wouldn't that just be `string`? Also `inputValidator` can return no validation error (indicated by a falsy value), so if I substitute `string | void` for `ValidationError` would that be valid?

```
inputValidator?: (input: any) => Promise<string | void> | string | void;
```

Similarly `preConfirm` can return a promise with a `void` resolution value type, so this is valid right?
```
preConfirm?: (inputValue: any) => Promise<any | void> | any | void;
```

**Comment by zenflow** [comment]
@toverux My bad. I see the `ValidationError` in your snippet now.

**Comment by zenflow** [comment]
@toverux Is this valid and explicit (and ok)?

```
inputValidator?: (inputValue: any) => Promise<string | void> | string | void;
preConfirm?: (inputValue: any) => Promise<any | void> | any | void;
```

**Comment by toverux** [comment]
`null` is not assignable to `void` :)
With `void`, you can only `return;`. I know that the lack of value on return will return `undefined` in JS (which is assignable to null), but `void` shows the intent that a value _should not be returned_ because it'll be discarded. In our case, we use the value returned by inputValidator/preConfirm, so we should use null instead of void. It'll force the API consumer to be explicit and use `return null`; (or `return undefined;`) which is not bad and "expected" in TypeScript.

**Comment by zenflow** [comment]
@toverux Thanks for explaining the difference! I think I've got it now. Using `null` for `inputValidator` since it's expected to return *something* (null and undefined included). Using `void` for `preConfirm` (as in your example) since it can simply `return;` and there's no real significance of `return null;` or `return undefined;`

**Pull request merged**
