### PR TITLE
Type-check and lint the TypeScript declaration file

### PR DESCRIPTION
**Pull request by toverux**
It's time to be safer! :)

The PR consists of a few minor improvements ; most importantly, `sweetalert2.d.ts` will now be type-checked by TypeScript (meaning that invalid syntax or static typing mistakes will be caught before they are publicated to npm), and tslint will lint the file (I fixed the code style errors at the same time).

:warning: I didn't commited the package-lock.json. It's the very first time I try to use npm 5 over yarn and boom, I see that npm is still quite inconsitent regarding its own lockfile: https://github.com/npm/npm/issues/17979 / https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json
When I ran "npm i", npm ignored and then rewrote the package-lock.json, which should just not happen. So I didn't commited it since I don't really know how you want to keep it up to date, @limonte.

### CODE REVIEW

**Comment by limonte** [comment]
> It's time to be safer! :)
> 
> The PR consists of a few minor improvements ; most importantly, sweetalert2.d.ts will now be type-checked by TypeScript (meaning that invalid syntax or static typing mistakes will be caught before they are publicated to npm), and tslint will lint the file (I fixed the code style errors at the same time).

I love linters! Robots should lint our code, and hopefully in near future even automatically [format it](https://medium.freecodecamp.org/why-robots-should-format-our-code-159fd06d17f7).

> :warning: I didn't commited the package-lock.json. It's the very first time I try to use npm 5 over yarn and boom, I see that npm is still quite inconsitent regarding its own lockfile: npm/npm#17979 / https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json
When I ran "npm i", npm ignored and then rewrote the package-lock.json, which should just not happen. So I didn't commited it since I don't really know how you want to keep it up to date, @limonte.

Yeah, JS ecosystem is sometimes quite weird, bringing breaking changes in minor releases is ridiculous for the "default" package manager. 

But when I figured out that npm reverted the behavior in v5.4.2 (patch release!!!) I totally lost my hope for npm and I'll stick to Yarn for my projects, at least in near future.

**Comment by toverux** [comment]
Semi-reverted, because, like other users, 5.4.2 still behaves incorrectly on my machine :smile: It's understandable that yarn had gained so much traction, that's not the first time npm betrays me.
Thanks for the merge!

**Comment by limonte** [comment]
Let's indicate to the community that Yarn is the better choice for package management: https://github.com/limonte/sweetalert2/commit/45e59f1ff86700022cadcdf81a8a490cac3f3af6

**Comment by toverux** [comment]
Good choice! Love the commit description :joy:

**Pull request merged**
